# Generated by Django 6.0.3 on 2026-03-31 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestItems',
            new_name='RequestItem',
        ),
    ]
