# Generated by Django 6.0.3 on 2026-05-01 09:38

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_product_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'ordering': ['-is_main'], 'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.AddField(
            model_name='request',
            name='waybill_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2026, 5, 1, 9, 38, 3, 847806, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
